### ISSUE TITLE
Seems to be kind of broken in the current Pale Moon

### ISSUE THREAD

**Issue by stickynoteme** [JustOff/save-images-me#1]
Hotkeys are not being saved and have to be set with every use, and all the menu options do nothing but open the options menu.

The extension seems to work fine still, but without the ability to use the menus options and having to setup the hotkeys with every browser restart it's a little hardcore.

**Comment by JustOff** [comment]
> Hotkeys are not being saved and have to be set with every use

I can't confirm this, for me the hotkeys are saved after restarts just fine.

> all the menu options do nothing but open the options menu.

Unfortunately  I don't understand what you mean, please provide more details.

**Comment by stickynoteme** [comment]
Set a hotkey:
Example: Ctrl+Right Arrow to save all tabs to the right.
Restart Palmoon
Hotkey will be reset to nothing.
